name: verdure
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.13.1 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.10.0
  test: ^1.16.0

dependencies: 
  flutter:
    sdk: flutter
  equatable: ^2.0.3
  uuid: ^3.0.0
  flutter_bloc: ^7.0.1
  firebase_core: "^1.3.0"
  formz: ^0.4.0
  sqflite: ^2.0.0+3
  path: ^1.8.0
  intl: ^0.17.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/database/
    - assets/image/